### ISSUE TITLE
Add MessagePack encoding

### ISSUE THREAD

**Issue by nsoblath** [project8/mantis#36]

**Comment by laroque** [comment]
Some notes from Noah:

just put the contents of msgpack-c/*.h as mantis/msgpack-c/*.h

make classes param_input_msgpack and param_output_msgpack to do the necessary conversions.  see Common/mt_param.hh after line 403. it can go in its own .hh/cc files, and we'll put the json conversion in its own files, too

**Comment by nsoblath** [comment]
Conversion from msgpack to param has been implemented.  At some point it would be nice to also get the conversion in the other direction in place, too, for completeness.  At this point, though, this is probably fairly low priority until we want Mantis to be able to transmit back to a client in msgpack.

**Comment by laroque** [comment]
Transmitting back in msgpack would be nice for consistency but is non-crucial since dripline.core.message now supports decoding application/json.

I'm closing this issue and opening a new one ( #41 ) for the conversion in the other direction since I don't think that that feature will be prioritized enough for mantis 3.0.
